export interface CountryInfo {
  name: string;
  capital: string;
  population: string;
  coordinates: [number, number];
  description: string;
}

const COUNTRIES: Record<string, CountryInfo> = {
  "Algeria": {
    name: "Algeria",
    capital: "Algiers",
    population: "45 million",
    coordinates: [3.0588, 36.7538],
    description: "Algeria is the largest country in Africa, located in North Africa along the Mediterranean coast. The national football team, known as Les Fennecs (The Desert Foxes), won the Africa Cup of Nations in 2019 and previously in 1990.",
  },
  "Argentina": {
    name: "Argentina",
    capital: "Buenos Aires",
    population: "46 million",
    coordinates: [-58.3816, -34.6037],
    description: "Argentina is a South American nation known for its passionate football culture. The national team, La Albiceleste, has won three FIFA World Cups (1978, 1986, 2022) and produced legends such as Diego Maradona and Lionel Messi.",
  },
  "Australia": {
    name: "Australia",
    capital: "Canberra",
    population: "26 million",
    coordinates: [149.1300, -35.2809],
    description: "Australia is a continent and country in the Southern Hemisphere. The Socceroos have qualified for six FIFA World Cups and reached the Round of 16 in 2022. Football is one of the fastest-growing sports in the country.",
  },
  "Austria": {
    name: "Austria",
    capital: "Vienna",
    population: "9.1 million",
    coordinates: [16.3738, 48.2082],
    description: "Austria is a landlocked country in Central Europe known for its alpine scenery and imperial history. Das Team has a rich footballing tradition and co-hosted UEFA Euro 2008 with Switzerland.",
  },
  "Belgium": {
    name: "Belgium",
    capital: "Brussels",
    population: "11.6 million",
    coordinates: [4.3517, 50.8503],
    description: "Belgium is a Western European country at the crossroads of Germanic and Latin cultures. The Red Devils reached the FIFA World Cup semi-finals in 2018 and have consistently ranked among the world's top national teams.",
  },
  "Bosnia & Herzegovina": {
    name: "Bosnia & Herzegovina",
    capital: "Sarajevo",
    population: "3.2 million",
    coordinates: [18.4131, 43.8563],
    description: "Bosnia and Herzegovina is a country on the Balkan Peninsula in southeastern Europe. The Dragons made their first FIFA World Cup appearance in 2014 in Brazil, reflecting the country's growing football pedigree.",
  },
  "Brazil": {
    name: "Brazil",
    capital: "Brasilia",
    population: "214 million",
    coordinates: [-47.8825, -15.7942],
    description: "Brazil is the largest country in South America and the most successful nation in World Cup history with five titles (1958, 1962, 1970, 1994, 2002). The Seleção is renowned for its creative, attacking style of play.",
  },
  "Canada": {
    name: "Canada",
    capital: "Ottawa",
    population: "40 million",
    coordinates: [-75.6972, 45.4215],
    description: "Canada is the second-largest country in the world by total area. As a co-host of the 2026 FIFA World Cup, the Canadian men's national team qualified for their second-ever World Cup after a 36-year absence in 2022.",
  },
  "Cape Verde": {
    name: "Cape Verde",
    capital: "Praia",
    population: "600,000",
    coordinates: [-23.5087, 14.933],
    description: "Cape Verde is an archipelago of ten volcanic islands in the central Atlantic Ocean off the western coast of Africa. The Blue Sharks have become a rising force in African football, qualifying for multiple Africa Cup of Nations tournaments.",
  },
  "Colombia": {
    name: "Colombia",
    capital: "Bogota",
    population: "52 million",
    coordinates: [-74.0721, 4.7110],
    description: "Colombia is a country in northwestern South America with coastlines on both the Caribbean Sea and the Pacific Ocean. Los Cafeteros are known for their flair and reached the 2014 World Cup quarter-finals behind James Rodriguez.",
  },
  "Croatia": {
    name: "Croatia",
    capital: "Zagreb",
    population: "3.9 million",
    coordinates: [15.9819, 45.8150],
    description: "Croatia is a country at the crossroads of Central and Southeast Europe on the Adriatic Sea. The Vatreni finished as World Cup runners-up in 2018 and third in 2022, a remarkable achievement for a nation of under four million people.",
  },
  "Curaçao": {
    name: "Curaçao",
    capital: "Willemstad",
    population: "150,000",
    coordinates: [-68.9900, 12.1696],
    description: "Curaçao is an island country in the southern Caribbean Sea, part of the ABC islands near the Venezuelan coast. The national football team has seen rapid growth, qualifying for the CONCACAF Gold Cup knockout rounds in recent years.",
  },
  "Czech Republic": {
    name: "Czech Republic",
    capital: "Prague",
    population: "10.8 million",
    coordinates: [14.4378, 50.0755],
    description: "The Czech Republic is a landlocked country in Central Europe, historically known as Bohemia. The national team finished as runners-up at UEFA Euro 1996 and reached the semi-finals of Euro 2004.",
  },
  "DR Congo": {
    name: "DR Congo",
    capital: "Kinshasa",
    population: "102 million",
    coordinates: [15.2663, -4.4419],
    description: "The Democratic Republic of the Congo is the second-largest country in Africa by area. The Leopards won the Africa Cup of Nations twice (1968, 1974) and became the first Sub-Saharan African team to compete in a FIFA World Cup in 1974.",
  },
  "Ecuador": {
    name: "Ecuador",
    capital: "Quito",
    population: "18 million",
    coordinates: [-78.4678, -0.1807],
    description: "Ecuador is a country straddling the equator on South America's west coast. La Tri have qualified for four FIFA World Cups and reached the Round of 16 in 2006, powered by high-altitude home matches in Quito.",
  },
  "Egypt": {
    name: "Egypt",
    capital: "Cairo",
    population: "105 million",
    coordinates: [31.2357, 30.0444],
    description: "Egypt is a transcontinental country spanning northeast Africa and southwest Asia. The Pharaohs are the most successful team in Africa Cup of Nations history with seven titles and produced Mohamed Salah, one of the world's top players.",
  },
  "England": {
    name: "England",
    capital: "London",
    population: "56 million",
    coordinates: [-0.1276, 51.5074],
    description: "England is the birthplace of modern football and home to the Premier League, the world's most-watched football league. The Three Lions won the 1966 FIFA World Cup and reached the Euro 2020 final at Wembley Stadium.",
  },
  "France": {
    name: "France",
    capital: "Paris",
    population: "68 million",
    coordinates: [2.3522, 48.8566],
    description: "France is a Western European country with a rich footballing heritage. Les Bleus have won two FIFA World Cups (1998, 2018) and two European Championships, and were runners-up at the 2022 World Cup in Qatar.",
  },
  "Germany": {
    name: "Germany",
    capital: "Berlin",
    population: "84 million",
    coordinates: [13.4050, 52.5200],
    description: "Germany is a country in Central Europe and one of football's most successful nations. Die Mannschaft has won four FIFA World Cups (1954, 1974, 1990, 2014) and three European Championships.",
  },
  "Ghana": {
    name: "Ghana",
    capital: "Accra",
    population: "33 million",
    coordinates: [-0.1870, 5.6037],
    description: "Ghana is a West African country along the Gulf of Guinea. The Black Stars became the third African team to reach the World Cup quarter-finals in 2010, narrowly missing the semi-finals in a dramatic match against Uruguay.",
  },
  "Haiti": {
    name: "Haiti",
    capital: "Port-au-Prince",
    population: "11.6 million",
    coordinates: [-72.3388, 18.5944],
    description: "Haiti occupies the western third of the island of Hispaniola in the Caribbean. Les Grenadiers made history by competing in the 1974 FIFA World Cup and have been a competitive force in Caribbean football.",
  },
  "Iran": {
    name: "Iran",
    capital: "Tehran",
    population: "87 million",
    coordinates: [51.3890, 35.6892],
    description: "Iran is a country in Western Asia. Team Melli is the most successful national team in Asian football, having qualified for six FIFA World Cups. They are three-time AFC Asian Cup champions.",
  },
  "Iraq": {
    name: "Iraq",
    capital: "Baghdad",
    population: "43 million",
    coordinates: [44.3661, 33.3152],
    description: "Iraq is a country in Western Asia. The Lions of Mesopotamia achieved their greatest sporting triumph by winning the 2007 AFC Asian Cup during a period of significant national hardship, uniting the country in celebration.",
  },
  "Ivory Coast": {
    name: "Ivory Coast",
    capital: "Yamoussoukro",
    population: "28 million",
    coordinates: [-5.3600, 6.8276],
    description: "Ivory Coast is a West African country with a southern coastline on the Gulf of Guinea. Les Éléphants won the Africa Cup of Nations in 2015 and 2023, and produced Didier Drogba, one of Africa's greatest-ever players.",
  },
  "Japan": {
    name: "Japan",
    capital: "Tokyo",
    population: "125 million",
    coordinates: [139.6917, 35.6895],
    description: "Japan is an island country in East Asia. The Samurai Blue co-hosted the 2002 FIFA World Cup and have qualified for every World Cup since 1998, reaching the Round of 16 four times including shock wins over Germany and Spain in 2022.",
  },
  "Jordan": {
    name: "Jordan",
    capital: "Amman",
    population: "11 million",
    coordinates: [35.9106, 31.9454],
    description: "Jordan is a country in Western Asia on the east bank of the Jordan River. Al-Nashama reached the AFC Asian Cup final for the first time in 2023, signaling their emergence as a competitive force in Asian football.",
  },
  "Mexico": {
    name: "Mexico",
    capital: "Mexico City",
    population: "129 million",
    coordinates: [-99.1332, 19.4326],
    description: "Mexico is a country in the southern portion of North America and a co-host of the 2026 FIFA World Cup. El Tri has qualified for 17 World Cups and hosted the tournament twice (1970, 1986). The Estadio Azteca is the only stadium to host two World Cup finals.",
  },
  "Morocco": {
    name: "Morocco",
    capital: "Rabat",
    population: "37 million",
    coordinates: [-6.8498, 34.0209],
    description: "Morocco is a North African country bordering the Atlantic Ocean and Mediterranean Sea. The Atlas Lions made history at the 2022 World Cup by becoming the first African and Arab nation to reach the semi-finals.",
  },
  "Netherlands": {
    name: "Netherlands",
    capital: "Amsterdam",
    population: "17.8 million",
    coordinates: [4.9041, 52.3676],
    description: "The Netherlands is a country in Northwestern Europe known for its pioneering Total Football philosophy. Oranje has reached three World Cup finals (1974, 1978, 2010) and won the European Championship in 1988.",
  },
  "New Zealand": {
    name: "New Zealand",
    capital: "Wellington",
    population: "5.1 million",
    coordinates: [174.7762, -41.2865],
    description: "New Zealand is an island country in the southwestern Pacific Ocean. The All Whites have competed in two FIFA World Cups (1982, 2010) and remain the only unbeaten team in 2010 World Cup history, drawing all three group matches.",
  },
  "Norway": {
    name: "Norway",
    capital: "Oslo",
    population: "5.5 million",
    coordinates: [10.7522, 59.9139],
    description: "Norway is a Nordic country on the Scandinavian Peninsula in Northern Europe. The national team qualified for three consecutive World Cups in the 1990s and famously defeated Brazil 2-1 in the 1998 group stage.",
  },
  "Panama": {
    name: "Panama",
    capital: "Panama City",
    population: "4.4 million",
    coordinates: [-79.5197, 8.9824],
    description: "Panama is a country in Central America bridging North and South America. Los Canaleros made their historic FIFA World Cup debut in 2018 in Russia, qualifying ahead of the United States in CONCACAF.",
  },
  "Paraguay": {
    name: "Paraguay",
    capital: "Asuncion",
    population: "7.4 million",
    coordinates: [-57.5759, -25.2637],
    description: "Paraguay is a landlocked country in central South America. La Albirroja reached the World Cup quarter-finals in 2010 and has qualified for eight World Cups, known for their defensive resilience and fighting spirit.",
  },
  "Portugal": {
    name: "Portugal",
    capital: "Lisbon",
    population: "10.3 million",
    coordinates: [-9.1393, 38.7223],
    description: "Portugal is a Southern European country on the Iberian Peninsula. The Seleção won UEFA Euro 2016 and the inaugural Nations League in 2019, and has produced Cristiano Ronaldo, one of the greatest players in football history.",
  },
  "Qatar": {
    name: "Qatar",
    capital: "Doha",
    population: "2.9 million",
    coordinates: [51.5310, 25.2854],
    description: "Qatar is a peninsula on the northeastern coast of the Arabian Peninsula in Western Asia. The Maroons hosted the 2022 FIFA World Cup and won the AFC Asian Cup in 2019 and 2023.",
  },
  "Saudi Arabia": {
    name: "Saudi Arabia",
    capital: "Riyadh",
    population: "36 million",
    coordinates: [46.6753, 24.7136],
    description: "Saudi Arabia is the largest country in the Arabian Peninsula. The Green Falcons shocked the world by defeating eventual champions Argentina 2-1 in the 2022 World Cup group stage, one of the greatest upsets in tournament history.",
  },
  "Scotland": {
    name: "Scotland",
    capital: "Edinburgh",
    population: "5.5 million",
    coordinates: [-3.1883, 55.9533],
    description: "Scotland is a country in the north of Great Britain and one of football's founding nations. The Tartan Army qualified for Euro 2020 after a 23-year absence from major tournaments, and Scottish clubs have a storied European history.",
  },
  "Senegal": {
    name: "Senegal",
    capital: "Dakar",
    population: "17 million",
    coordinates: [-17.4677, 14.7167],
    description: "Senegal is a country on the west coast of Africa. The Lions of Teranga reached the 2002 World Cup quarter-finals in their debut appearance and won the Africa Cup of Nations in 2021 under coach Aliou Cissé.",
  },
  "South Africa": {
    name: "South Africa",
    capital: "Pretoria",
    population: "60 million",
    coordinates: [28.1871, -25.7461],
    description: "South Africa is the southernmost country on the African continent. Bafana Bafana hosted the 2010 FIFA World Cup, the first on the African continent, and won the Africa Cup of Nations in 1996.",
  },
  "South Korea": {
    name: "South Korea",
    capital: "Seoul",
    population: "52 million",
    coordinates: [126.9780, 37.5665],
    description: "South Korea is a country in East Asia constituting the southern half of the Korean Peninsula. The Taegeuk Warriors co-hosted the 2002 World Cup and reached the semi-finals, the best result by any Asian team in tournament history.",
  },
  "Spain": {
    name: "Spain",
    capital: "Madrid",
    population: "47 million",
    coordinates: [-3.7038, 40.4168],
    description: "Spain is a country on the Iberian Peninsula in Southern Europe. La Roja won the 2010 FIFA World Cup and back-to-back European Championships in 2008 and 2012, dominating world football with their tiki-taka style.",
  },
  "Sweden": {
    name: "Sweden",
    capital: "Stockholm",
    population: "10.5 million",
    coordinates: [18.0686, 59.3293],
    description: "Sweden is a Nordic country in Northern Europe on the Scandinavian Peninsula. The Blågult have appeared in 12 World Cups and finished as runners-up in 1958 when they hosted the tournament, and reached the quarter-finals in 2018.",
  },
  "Switzerland": {
    name: "Switzerland",
    capital: "Bern",
    population: "8.8 million",
    coordinates: [7.4474, 46.9480],
    description: "Switzerland is a landlocked country at the confluence of Western, Central, and Southern Europe. The Nati have qualified for five consecutive World Cups and co-hosted Euro 2008 with Austria.",
  },
  "Tunisia": {
    name: "Tunisia",
    capital: "Tunis",
    population: "12 million",
    coordinates: [10.1658, 36.8065],
    description: "Tunisia is a country in the Maghreb region of North Africa. The Eagles of Carthage have qualified for six FIFA World Cups and defeated France in the 2022 group stage. They won the Africa Cup of Nations in 2004.",
  },
  "Turkey": {
    name: "Turkey",
    capital: "Ankara",
    population: "85 million",
    coordinates: [32.8597, 39.9334],
    description: "Turkey is a transcontinental country straddling Southeast Europe and Western Asia. The national team achieved their best World Cup result with a third-place finish in 2002 and reached the Euro 2008 semi-finals.",
  },
  "Uruguay": {
    name: "Uruguay",
    capital: "Montevideo",
    population: "3.4 million",
    coordinates: [-56.1645, -34.9011],
    description: "Uruguay is a South American country known as the cradle of international football. La Celeste won the inaugural FIFA World Cup in 1930 and again in 1950, and have won a record 15 Copa América titles.",
  },
  "USA": {
    name: "United States",
    capital: "Washington, D.C.",
    population: "335 million",
    coordinates: [-77.0369, 38.9072],
    description: "The United States is a co-host of the 2026 FIFA World Cup, the first expanded 48-team tournament. The USMNT reached the World Cup quarter-finals in 2002 and have qualified for 11 World Cups.",
  },
  "Uzbekistan": {
    name: "Uzbekistan",
    capital: "Tashkent",
    population: "35 million",
    coordinates: [69.2401, 41.2995],
    description: "Uzbekistan is a doubly landlocked country in Central Asia. The White Wolves are making their FIFA World Cup debut in 2026 after years of near-misses, and won the AFC U-20 Asian Cup in 2023.",
  },
};

export function getCountryInfo(team: string): CountryInfo | undefined {
  return COUNTRIES[team];
}
